### ISSUE TITLE
Can't build locally or on TravisCI

### ISSUE THREAD

**Issue by expede** [fission-suite/typescript-client#9]
# Problem

## Locally

```
src/fission-typescript.ts → dist/fission-typescript.umd.js, dist/fission-typescript.es5.js...
[!] Error: Could not resolve entry (src/fission-typescript.ts)
Error: Could not resolve entry (src/fission-typescript.ts)
    at error (/Users/expede/Documents/Work/FISSION/typescript-client/node_modules/rollup/dist/rollup.js:3460:30)
    at /Users/expede/Documents/Work/FISSION/typescript-client/node_modules/rollup/dist/rollup.js:21474:17
    at async Promise.all (index 0)
```

## Travis 

https://travis-ci.org/fission-suite/typescript-client/jobs/572969282

# Solution

Best guess: set `main: fission.ts`, &c in `package.json`

**Comment by dholms** [comment]
Resolved with: https://github.com/fission-suite/typescript-client/pull/10 & https://github.com/fission-suite/typescript-client/pull/11
